<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Appointments\" />
    <Folder Include="Customers\" />
    <Folder Include="Employees\" />
    <Folder Include="GardenPlots\" />
    <Folder Include="GardenSites\" />
    <Folder Include="Properties\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
